---

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create gitea run configuration
      ansible.builtin.template:
        src: "gitea.j2"
        dest: "{{ gitea_defaults_directory }}/gitea"
        force: true
        owner: root
        group: "{{ gitea_system_group }}"
        mode: 0640
      notify:
        - reload gitea

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/gitea.service.j2"
        dest: "{{ systemd_lib_directory }}/gitea.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/gitea.j2"
        dest: "/etc/conf.d/gitea"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/gitea.j2"
        dest: "/etc/init.d/gitea"
        owner: root
        group: root
        mode: 0750

- name: create gitea configuration
  ansible.builtin.template:
    force: true
    src: conf/app.ini.j2
    dest: "{{ gitea_config_dir }}/app.ini"
    owner: root
    group: "{{ gitea_system_group }}"
    mode: 0640
  register: gitea_config
  #notify:
  #  - validate config

- name: restart gitea if needed
  ansible.builtin.meta: flush_handlers

...
