---

- name: create gitea configuration directory
  ansible.builtin.file:
    path: "{{ gitea_config_dir }}"
    state: directory
    owner: root
    group: "{{ gitea_system_group }}"
    mode: 0770

- name: create gitea working directory
  ansible.builtin.file:
    path: "{{ gitea_working_dir }}"
    state: directory
    owner: root
    group: "{{ gitea_system_group }}"
    mode: 0770

- name: create gitea custom directory tree
  ansible.builtin.file:
    path: "{{ gitea_working_dir }}/{{ item }}"
    state: directory
    owner: root
    group: "{{ gitea_system_group }}"
    mode: 0770
  loop:
    - log
    - custom/options
    - data
    - data/gitea-repositories
    - data/lfs
    - data/home

- name: create gitea configuration
  ansible.builtin.template:
    force: true
    src: conf/gitea.ini.j2
    dest: "{{ gitea_config_dir }}/gitea.ini"
    owner: root
    group: "{{ gitea_system_group }}"
    mode: 0640
  register: gitea_config
  notify:
    - restart gitea

- name: restart gitea if needed
  ansible.builtin.meta: flush_handlers

- name: create admin user
  gitea_user:
    admin: true
    username: "{{ gitea_admin_user.username }}"
    password: "{{ gitea_admin_user.password }}"
    email: "{{ gitea_admin_user.email }}"

...
