---

- name: download gitea binary archive
  become: false
  delegate_to: "{{ gitea_delegate_to }}"
  run_once: "{{ 'false' if gitea_direct_download else 'true' }}"
  ansible.builtin.get_url:
    url: "{{ gitea_release_download_url }}/download/{{ __gitea_files.archive }}"
    dest: "{{ gitea_local_tmp_directory }}/{{ __gitea_files.binary }}"
    mode: 0644
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

...
