---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yaml
      skip: true



- name: install dependency
  ansible.builtin.package:
    name: "{{ gitea_requirements }}"
    state: present




- name: detect installed gitea binary {{ gitea_install_path }}/gitea
  ansible.builtin.stat:
    path: "{{ gitea_install_path }}/gitea"
  register: stat_gitea_binary





- name: merge gitea configuration between defaults and custom
  ansible.builtin.set_fact:
    gitea_actions: "{{ gitea_defaults_actions | combine(gitea_actions, recursive=True) }}"
    gitea_admin: "{{ gitea_defaults_admin | combine(gitea_admin, recursive=True) }}"
    gitea_api: "{{ gitea_defaults_api | combine(gitea_api, recursive=True) }}"
    gitea_attachment: "{{ gitea_defaults_attachment | combine(gitea_attachment, recursive=True) }}"
    gitea_cache: "{{ gitea_defaults_cache | combine(gitea_cache, recursive=True) }}"
    gitea_camo: "{{ gitea_defaults_camo | combine(gitea_camo, recursive=True) }}"
    gitea_cron: "{{ gitea_defaults_cron | combine(gitea_cron, recursive=True) }}"
    gitea_database: "{{ gitea_defaults_database | combine(gitea_database, recursive=True) }}"
    gitea_federation: "{{ gitea_defaults_federation | combine(gitea_federation, recursive=True) }}"
    gitea_git: "{{ gitea_defaults_git | combine(gitea_git, recursive=True) }}"
    gitea_highlight: "{{ gitea_defaults_highlight | combine(gitea_highlight, recursive=True) }}"
    gitea_i18n: "{{ gitea_defaults_i18n | combine(gitea_i18n, recursive=True) }}"
    gitea_indexer: "{{ gitea_defaults_indexer | combine(gitea_indexer, recursive=True) }}"
    gitea_log: "{{ gitea_defaults_log | combine(gitea_log, recursive=True) }}"
    gitea_mailer: "{{ gitea_defaults_mailer | combine(gitea_mailer, recursive=True) }}"
    gitea_markdown: "{{ gitea_defaults_markdown | combine(gitea_markdown, recursive=True) }}"
    gitea_markup: "{{ gitea_defaults_markup | combine(gitea_markup, recursive=True) }}"
    gitea_metrics: "{{ gitea_defaults_metrics | combine(gitea_metrics, recursive=True) }}"
    gitea_migrations: "{{ gitea_defaults_migrations | combine(gitea_migrations, recursive=True) }}"
    gitea_mirror: "{{ gitea_defaults_mirror | combine(gitea_mirror, recursive=True) }}"
    gitea_oauth2: "{{ gitea_defaults_oauth2 | combine(gitea_oauth2, recursive=True) }}"
    gitea_oauth2_client: "{{ gitea_defaults_oauth2_client | combine(gitea_oauth2_client, recursive=True) }}"
    gitea_openid: "{{ gitea_defaults_openid | combine(gitea_openid, recursive=True) }}"
    gitea_other: "{{ gitea_defaults_other | combine(gitea_other, recursive=True) }}"
    gitea_packages: "{{ gitea_defaults_packages | combine(gitea_packages, recursive=True) }}"
    gitea_picture: "{{ gitea_defaults_picture | combine(gitea_picture, recursive=True) }}"
    gitea_project: "{{ gitea_defaults_project | combine(gitea_project, recursive=True) }}"
    gitea_proxy: "{{ gitea_defaults_proxy | combine(gitea_proxy, recursive=True) }}"
    gitea_queue: "{{ gitea_defaults_queue | combine(gitea_queue, recursive=True) }}"
    gitea_repository: "{{ gitea_defaults_repository | combine(gitea_repository, recursive=True) }}"
    gitea_security: "{{ gitea_defaults_security | combine(gitea_security, recursive=True) }}"
    gitea_server: "{{ gitea_defaults_server | combine(gitea_server, recursive=True) }}"
    gitea_service: "{{ gitea_defaults_service | combine(gitea_service, recursive=True) }}"
    gitea_session: "{{ gitea_defaults_session | combine(gitea_session, recursive=True) }}"
    gitea_ssh: "{{ gitea_defaults_ssh | combine(gitea_ssh, recursive=True) }}"
    gitea_storage: "{{ gitea_defaults_storage | combine(gitea_storage, recursive=True) }}"
    gitea_task: "{{ gitea_defaults_task | combine(gitea_task, recursive=True) }}"
    gitea_time: "{{ gitea_defaults_time | combine(gitea_time, recursive=True) }}"
    gitea_ui: "{{ gitea_defaults_ui | combine(gitea_ui, recursive=True) }}"
    gitea_webhook: "{{ gitea_defaults_webhook | combine(gitea_webhook, recursive=True) }}"

...
